name: Build Mac OS X Lion ISO (10.7) - Python

on:
  workflow_dispatch:

jobs:
  lion-iso:
    runs-on: macos-15-intel
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout Lion repository
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/Mac-OS-X-Lion-Installer-11A511"
          path: "${{ github.workspace }}/temp/"
          token: "${{ secrets.PAT }}"

      - name: Stitch DMG parts and save to Workspace
        run: |
          cat ${{ github.workspace }}/temp/Lion.dmg.part* > ${{ github.workspace }}/Lion.dmg
          
          rm -rf ${{ github.workspace }}/temp/
        
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Download and create Lion ISO (11A511)
        run: |
          python ${{ github.workspace }}/macos-iso.py lion
        env:
          FILEPATH: "${{ github.workspace }}/"
