name: Build Mac OS X Lion ISO (10.7) - Python

on:
  workflow_dispatch:

jobs:
  lion-iso:
    runs-on: macos-15-intel
    timeout-minutes: 360
    steps:
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Download and create Lion ISO (11A511)
        run: |
          python ${{ github.workspace }}/macos-iso.py lion
        env:
          FILEPATH: "${{ github.workspace }}/"
