name: Build macOS Sequoia ISO (24A335)

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: "${{ github.workspace }}/"

      - name: Checkout PKG branch
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/MacOS-Sequoia-24A335"
          ref: "PKG"
          path: "${{ github.workspace }}/PKG"
          token: "${{ secrets.PAT }}"

      - name: Checkout ISO branch
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/MacOS-Sequoia-24A335"
          ref: "ISO"
          path: "${{ github.workspace }}/ISO"
          token: "${{ secrets.PAT }}"

      - name: Checkout DMG branch
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/MacOS-Sequoia-24A335"
          ref: "DMG"
          path: "${{ github.workspace }}/DMG"
          token: "${{ secrets.PAT }}"

      - name: Checkout IMG branch
        uses: actions/checkout@v6
        with:
          repository: "${{ github.repository_owner }}/MacOS-Sequoia-24A335"
          ref: "IMG"
          path: "${{ github.workspace }}/IMG"
          token: "${{ secrets.PAT }}"

      - name: Set up Git
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"

          git config --global user.name "AllanVester"
          git config --global user.email "vesterallan246@gmail.com"
          git config --global http.postBuffer 104857600

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Download macrecovery.py
        run: |
          until curl -f -L -C - -o ${{ github.workspace }}/macrecovery.py "https://raw.githubusercontent.com/acidanthera/OpenCorePkg/refs/heads/master/Utilities/macrecovery/macrecovery.py"; do
            echo "Download failed or interrupted. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Download macOS Sequoia BaseSystem.dmg 
        run: |
          sed -i.bak 's/os.get_terminal_size().columns/80/g' macrecovery.py
          sed -i.bak 's/com.apple.recovery.boot/./g' macrecovery.py
          
          python3 macrecovery.py -b Mac-226CB3C6A851A671 -m 00000000000000000 download

      - name: Split DMG into 100MB chunks
        run: |
          ls -lh ${{ github.workspace }}/BaseSystem.dmg
          
          split -a 3 -b 100m -d "${{ github.workspace }}/BaseSystem.dmg" "${{ github.workspace }}/DMG/Sequoia.dmg.part"

      - name: Upload DMG to GitHub
        working-directory: "${{ github.workspace }}/DMG/"
        run: |
          for file in Sequoia.dmg.part*; do
              git add "$file"
              git commit -m "Uploaded $file"
              git push
          done

      - name: ConvertmacOS Sequoia BaseSystem.dmg to BaseSystem.img
        run: |
          brew install dmg2img

          dmg2img -i ${{ github.workspace }}/BaseSystem.dmg -o ${{ github.workspace }}/Sequoia.img

      - name: Split IMG into 100MB chunks
        run: |
          split -a 3 -b 100m -d ${{ github.workspace }}/Sequoia.img ${{ github.workspace }}/IMG/Sequoia.img.part

      - name: Upload IMG to GitHub
        working-directory: "${{ github.workspace }}/IMG/"
        run: |
          for file in Sequoia.img.part*; do
              git add "$file"
              git commit -m "Uploaded $file"
              git push
          done

      - name: Download macOS Sequoia Installer 
        run: |
          until curl -f -L -C - -o ${{ github.workspace }}/InstallAssistant.pkg "https://archive.org/download/macOS-24A335-InstallAssistant/InstallAssistant.pkg"; do
            echo "Download failed or interrupted. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Split PKG into 100MB chunks
        run: |
          split -a 3 -b 100m -d ${{ github.workspace }}/InstallAssistant.pkg ${{ github.workspace }}/PKG/Sequoia.pkg.part

      - name: Upload PKG to GitHub
        working-directory: "${{ github.workspace }}/PKG/"
        run: |
          for file in Sequoia.pkg.part*; do
              git add "$file"
              git commit -m "Uploaded $file"
              git push
          done

      - name: Split PKG directory
        run: |
          rm -rf ${{ github.workspace }}/PKG

      - name: Install the Installer App
        run: |
          echo "Installing package..."
          sudo installer -pkg ${{ github.workspace }}/InstallAssistant.pkg -target /
          
          # Verify it exists
          ls -d /Applications/Install\ macOS\ Sequoia*.app

          # Delete the pkg to save space immediately
          rm ${{ github.workspace }}/InstallAssistant.pkg

      - name: Create and Mount Disk Image
        run: |
          echo "Creating empty disk image..."
          # Use a sparse image to save space until it's filled
          hdiutil create -o /tmp/Sequoia -size 18432m -volname Sequoia -layout SPUD -fs HFS+J
          
          echo "Mounting disk image..."
          hdiutil attach /tmp/Sequoia.dmg -noverify -mountpoint /Volumes/Sequoia

      - name: Create Install Media
        run: |
          echo "Running createinstallmedia (this takes time)..."
          # We use a wildcard (*) because the app name might vary slightly (e.g. "beta")
          INSTALLER_PATH=$(find /Applications -name "Install macOS Sequoia*.app" -maxdepth 1 | head -n 1)
          echo "Found installer at: $INSTALLER_PATH"
          
          sudo "$INSTALLER_PATH/Contents/Resources/createinstallmedia" --volume /Volumes/Sequoia --nointeraction

      - name: Unmount and Convert to ISO
        run: |
          echo "Unmounting..."
          hdiutil detach /Volumes/Install\ macOS\ Sequoia*
          
          echo "Converting to ISO/CDR..."
          hdiutil convert /tmp/Sequoia.dmg -format UDTO -o ${{ github.workspace }}/Sequoia.cdr
          
          echo "Renaming to .iso..."
          mv ${{ github.workspace }}/Sequoia.cdr ${{ github.workspace }}/Sequoia.iso
          
          ls -lh ${{ github.workspace }}/Sequoia.iso

      - name: Split ISO into 100MB chunks
        run: |
          split -a 3 -b 100m -d ${{ github.workspace }}/Sequoia.iso ${{ github.workspace }}/ISO/Sequoia.iso.part

      - name: Upload ISO to GitHub
        working-directory: "${{ github.workspace }}/ISO/"
        run: |
          for file in Sequoia.iso.part*; do
              git add "$file"
              git commit -m "Uploaded $file"
              git push
          done
